namespace BlamTags;

/// <summary>
/// Resolved type of a layout field — the dispatch-ready enum form of a
/// field's type-name string, computed once per field during layout read so
/// the hot read/write paths dispatch on an enum instead of comparing
/// strings. Variant names mirror the Halo type-name strings (e.g.
/// <c>"real point 3d"</c> → <see cref="RealPoint3d"/>). <see cref="Unknown"/>
/// is the fallback for any unrecognized name.
/// </summary>
public enum TagFieldType
{
    Unknown,
    String,
    LongString,
    StringId,
    OldStringId,
    CharInteger,
    ShortInteger,
    LongInteger,
    Int64Integer,
    ByteInteger,
    WordInteger,
    DwordInteger,
    QwordInteger,
    Angle,
    Tag,
    CharEnum,
    ShortEnum,
    LongEnum,
    LongFlags,
    WordFlags,
    ByteFlags,
    Point2d,
    Rectangle2d,
    RgbColor,
    ArgbColor,
    Real,
    RealSlider,
    RealFraction,
    RealPoint2d,
    RealPoint3d,
    RealVector2d,
    RealVector3d,
    RealQuaternion,
    RealEulerAngles2d,
    RealEulerAngles3d,
    RealPlane2d,
    RealPlane3d,
    RealRgbColor,
    RealArgbColor,
    RealHsvColor,
    RealAhsvColor,
    ShortIntegerBounds,
    AngleBounds,
    RealBounds,
    FractionBounds,
    TagReference,
    Block,
    LongBlockFlags,
    WordBlockFlags,
    ByteBlockFlags,
    CharBlockIndex,
    CustomCharBlockIndex,
    ShortBlockIndex,
    CustomShortBlockIndex,
    LongBlockIndex,
    CustomLongBlockIndex,
    Data,
    VertexBuffer,
    Pad,
    UselessPad,
    Skip,
    Explanation,
    Custom,
    Struct,
    Array,
    PageableResource,
    ApiInterop,
    Terminator,
    NonCacheRuntimeValue,
}

public static class TagFieldTypeExtensions
{
    /// <summary>
    /// Parse a field-type name string (the space-separated form stored in
    /// the layout's <c>string_data</c>) into the dispatch enum. Unknown
    /// names return <see cref="TagFieldType.Unknown"/> — that's how new or
    /// unhandled type names are detected without throwing.
    /// </summary>
    public static TagFieldType FromName(string name) => name switch
    {
        "string" => TagFieldType.String,
        "long string" => TagFieldType.LongString,
        "string id" => TagFieldType.StringId,
        "old string id" => TagFieldType.OldStringId,
        "char integer" => TagFieldType.CharInteger,
        "short integer" => TagFieldType.ShortInteger,
        "long integer" => TagFieldType.LongInteger,
        "int64 integer" => TagFieldType.Int64Integer,
        "byte integer" => TagFieldType.ByteInteger,
        "word integer" => TagFieldType.WordInteger,
        "dword integer" => TagFieldType.DwordInteger,
        "qword integer" => TagFieldType.QwordInteger,
        "angle" => TagFieldType.Angle,
        "tag" => TagFieldType.Tag,
        "char enum" => TagFieldType.CharEnum,
        "short enum" => TagFieldType.ShortEnum,
        "long enum" => TagFieldType.LongEnum,
        "long flags" => TagFieldType.LongFlags,
        "word flags" => TagFieldType.WordFlags,
        "byte flags" => TagFieldType.ByteFlags,
        "point 2d" => TagFieldType.Point2d,
        "rectangle 2d" => TagFieldType.Rectangle2d,
        "rgb color" => TagFieldType.RgbColor,
        "argb color" => TagFieldType.ArgbColor,
        "real" => TagFieldType.Real,
        "real slider" => TagFieldType.RealSlider,
        "real fraction" => TagFieldType.RealFraction,
        "real point 2d" => TagFieldType.RealPoint2d,
        "real point 3d" => TagFieldType.RealPoint3d,
        "real vector 2d" => TagFieldType.RealVector2d,
        "real vector 3d" => TagFieldType.RealVector3d,
        "real quaternion" => TagFieldType.RealQuaternion,
        "real euler angles 2d" => TagFieldType.RealEulerAngles2d,
        "real euler angles 3d" => TagFieldType.RealEulerAngles3d,
        "real plane 2d" => TagFieldType.RealPlane2d,
        "real plane 3d" => TagFieldType.RealPlane3d,
        "real rgb color" => TagFieldType.RealRgbColor,
        "real argb color" => TagFieldType.RealArgbColor,
        "real hsv color" => TagFieldType.RealHsvColor,
        "real ahsv color" => TagFieldType.RealAhsvColor,
        "short integer bounds" => TagFieldType.ShortIntegerBounds,
        "angle bounds" => TagFieldType.AngleBounds,
        "real bounds" => TagFieldType.RealBounds,
        "fraction bounds" => TagFieldType.FractionBounds,
        "tag reference" => TagFieldType.TagReference,
        "block" => TagFieldType.Block,
        "long block flags" => TagFieldType.LongBlockFlags,
        "word block flags" => TagFieldType.WordBlockFlags,
        "byte block flags" => TagFieldType.ByteBlockFlags,
        "char block index" => TagFieldType.CharBlockIndex,
        "custom char block index" => TagFieldType.CustomCharBlockIndex,
        "short block index" => TagFieldType.ShortBlockIndex,
        "custom short block index" => TagFieldType.CustomShortBlockIndex,
        "long block index" => TagFieldType.LongBlockIndex,
        "custom long block index" => TagFieldType.CustomLongBlockIndex,
        "data" => TagFieldType.Data,
        "vertex buffer" => TagFieldType.VertexBuffer,
        "pad" => TagFieldType.Pad,
        "useless pad" => TagFieldType.UselessPad,
        "skip" => TagFieldType.Skip,
        "explanation" => TagFieldType.Explanation,
        "custom" => TagFieldType.Custom,
        "struct" => TagFieldType.Struct,
        "array" => TagFieldType.Array,
        "pageable resource" => TagFieldType.PageableResource,
        "api interop" => TagFieldType.ApiInterop,
        "terminator X" => TagFieldType.Terminator,
        "non-cache runtime value" => TagFieldType.NonCacheRuntimeValue,
        _ => TagFieldType.Unknown,
    };
}
